libraries:
  active: true
  ForbiddenPublicDataClass:
    active: false
    ignorePackages:
      - '*.internal'
      - '*.internal.*'
  LibraryCodeMustSpecifyReturnType:
    active: true
    allowOmitUnit: false
  LibraryEntitiesShouldNotBePublic:
    active: false
